package rules

global com.baloise.open.devops.monitor.controller.infrastructure.drools.LogFactory log

import com.baloise.open.devops.monitor.controller.domain.model.Event
import com.baloise.open.devops.monitor.controller.domain.model.Situation

rule "Guidewire System Event Detection"
    when
        $event : Event( situation.tags.contains("GWR"))
    then
      	log.info("Event concerning Guidewire system: {}", $event.getUuid());
end

rule "Detect Instance-ID"
    when
        $event : Event($instanceId:affectedSystem.instanceId
                        && $instanceId.matches("https://(int-|test-|acc-)?target.balgroupit.com/(pc|bc|cc|ab)/.*"))
    then
        log.info("GWR-Instance ID: {}", $instanceId);
end
