@startuml
'https://plantuml.com/component-diagram

frame "DevOps Mon" {
    [Prometheus] as [prometheus]
    frame "Any Component"{
        [Micrometer] as [micrometer]
    }

    [DevOpsMon Gate] as [dom-gate]

    frame "Control"{
        [DevOpsMon Control] as [dom-control]
        [Rule Engine] as [rule-eng]

        [dom-control] --> [rule-eng] : process\nevents
    }

    frame "Workflow"{
        [DevOpsMon Workflow] as [dom-workflow]
        [Decision WF] as [decision-wf]
        [Action WF] as [action-wf]

        [dom-workflow] --> [decision-wf]
        [dom-workflow] --> [action-wf]
    }

    [Policy Center] as [gwr-pc]
    [Billing Center] as [gwr-bc]
    [Claim Center] as [gwr-cc]
    [Contact Manager] as [gwr-cm]

    database "Kafka" {
        frame "topics" {
            [Events] as [event]
            [Recommended\nAction] as [recommended-action]
        }
    }

    [micrometer] --> [prometheus] : provide\nmetrics
    [prometheus] --> [dom-gate] : provide\nalert

    [dom-gate] --> [event] : publish\nevent
    [event] --> [dom-control] : consume\nevent

    [dom-control] --> [recommended-action] : publish\nevent
    [recommended-action] --> [dom-workflow] : consume\nevent

    [gwr-pc] --> [dom-gate] : produce\nevent
    [gwr-bc] --> [dom-gate] : produce\nevent
    [gwr-cc] --> [dom-gate] : produce\nevent
    [gwr-cm] --> [dom-gate] : produce\nevent

    [dom-workflow] --> [gwr-pc] : action
    [dom-workflow] --> [gwr-bc] : action
    [dom-workflow] --> [gwr-cc] : action
    [dom-workflow] --> [gwr-cm] : action
}
@enduml