groups:
  - name: AllInstances
    rules:
      - alert: DummyAlert
        # Condition for alerting
        expr: jvm_buffer_memory_used_bytes
        for: 1m
        # Annotation - additional informational labels to store more information
        annotations:
          title: 'Instance {{ $labels.instance }} down'
          description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute.'
        # Labels - additional labels to be attached to the alert
        labels:
          severity: 'critical'
