### perform service call 1
http://localhost:8080/admin/service

### perform service call 2
http://localhost:8080/admin/service

### perform service call 3
http://localhost:8080/admin/service


### Modify fake CPU Usage
http://localhost:8080/admin/cpu/76


### receive prometheus alert
POST http://localhost:8080/event/create/prometheus
Content-Type: application/json

{
  "id": 999,
  "value": "content"
}